[package]
name = "advent-2021"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive-new = "0.5.9"
glam = "0.20.1"
itertools = "0.10.1"
lazy_static = "1.4.0"
ndarray = "0.15.4"
regex = "1.5.4"
